name: Build DFX Timer
on: [push, workflow_dispatch]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16 # Versão ideal para Electron 11

      - name: Instalar Dependências
        run: npm install --legacy-peer-deps

      - name: Gerar Executável
        # O segredo está nestas duas variáveis de ambiente abaixo
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: "--openssl-legacy-provider"
