name: Build DFX Timer
on: [push, workflow_dispatch]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Instalar Dependências
        run: npm install --legacy-peer-deps

      - name: Gerar Executável
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Removida a linha NODE_OPTIONS que causou o erro
